{
   "астрономия" : "sci_phys",
   "гадание, толкование снов" : "religion_esoterics",
   "внешнеэкономическая деятельность" : "global_economy",
   "книги про волшебников" : "magician_book",
   "иностранные языки" : "foreign_language",
   "легкая проза" : "russian_contemporary",
   "теория государства и права" : "sci_juris",
   "эксплуатация промышленного оборудования" : "sci_tech",
   "благоустройство территории" : "sci_tech",
   "органическая химия" : "sci_chem",
   "естествознание 10 класс" : "child_education",
   "общая психология" : "psy_generic",
   "биология 11 класс" : "child_education",
   "комиксы, манга" : "visual_arts",
   "химия" : "sci_chem",
   "русский язык 7 класс" : "child_education",
   "ноты" : "music_dancing",
   "экология 9 класс" : "child_education",
   "детские стихи" : "child_verse",
   "металловедение" : "sci_tech",
   "физическая химия" : "sci_chem",
   "документы, жалобы, образцы" : "sci_juris",
   "гендерные различия" : "management",
   "окружающий мир 1 класс" : "child_education",
   "любовно-фантастические романы" : "love_sf",
   "ЕГЭ по географии" : "child_education",
   "инновации в бизнесе" : "popular_business",
   "промышленный транспорт" : "sci_tech",
   "обществознание 7 класс" : "child_education",
   "производство металлических изделий" : "sci_tech",
   "изобразительное искусство (ИЗО) 2 класс" : "child_education",
   "психоанализ" : "psy_theraphy",
   "физкультура 6 класс" : "child_education",
   "бытовые справочники" : "ref_ref",
   "социальная фантастика" : "sf_social",
   "судебное право" : "sci_juris",
   "природоведение 5 класс" : "child_education",
   "классика менеджмента" : "management",
   "история 7 класс" : "child_education",
   "автожурналы" : "periodic",
   "йога" : "religion_esoterics",
   "эндокринология" : "sci_medicine",
   "прикладная литература" : "home",
   "биографии и мемуары" : "nonf_biography",
   "толковые словари" : "ref_dict",
   "черчение 9 класс" : "child_education",
   "иностранный язык 11 класс" : "child_education",
   "основы безопасности жизнедеятельности (ОБЖ) 9 класс" : "child_education",
   "риски" : "personal_finance",
   "логика" : "sci_philosophy",
   "религиоведение, история религий" : "sci_religion",
   "ЕГЭ по информатике и ИКТ" : "child_education",
   "практическая эзотерика" : "religion_esoterics",
   "школьные учебники по математике" : "child_education",
   "гражданский кодекс РФ" : "sci_juris",
   "проектирование" : "sci_tech",
   "физкультура 7 класс" : "child_education",
   "афоризмы и цитаты" : "aphorism_quote",
   "фтизиатрия и пульмонология" : "sci_medicine",
   "шпионские детективы" : "det_espionage",
   "пьесы и драматургия" : "dramaturgy",
   "чтение 1 класс" : "child_education",
   "общественно-политические журналы" : "periodic",
   "современные любовные романы" : "love_contemporary",
   "технология 6 класс" : "child_education",
   "лесное хозяйство" : "sci_biology",
   "физкультура 9 класс" : "child_education",
   "другие справочники" : "ref_ref",
   "ЕГЭ по химии" : "child_education",
   "русский язык 1 класс" : "child_education",
   "православные каноны" : "religion_rel",
   "технология 10 класс" : "child_education",
   "радиоэлектроника" : "sci_tech",
   "транспорт" : "sci_tech",
   "мерчендайзинг" : "marketing",
   "информатика 10 класс" : "child_education",
   "мировая экономика" : "economics",
   "ветеринария" : "sci_biology",
   "история России" : "sci_history",
   "житийная литература" : "religion",
   "информатика 8 класс" : "child_education",
   "физика 11 класс" : "child_education",
   "кинематограф, театр" : "cinema_theatre",
   "народная и нетрадиционная медицина" : "home_health",
   "книги для детей" : "children",
   "архитектурные конструкции" : "sci_tech",
   "научная фантастика" : "sf",
   "топливно-энергетический комплекс" : "sci_tech",
   "школьные учебники по истории" : "child_education",
   "молодежные журналы" : "periodic",
   "спортивные журналы" : "periodic",
   "информатика 3 класс" : "child_education",
   "международное право" : "sci_juris",
   "гражданский процессуальный кодекс РФ" : "sci_juris",
   "геометрия 8 класс" : "child_education",
   "триллеры" : "thriller",
   "культурология" : "sci_culture",
   "стимпанк" : "sf",
   "электроника" : "sci_tech",
   "буквари" : "child_education",
   "математика 2 класс" : "child_education",
   "архитектура" : "architecture_book",
   "зарубежная эзотерическая литература" : "foreign_religion",
   "полицейские детективы" : "det_police",
   "учебники 9 класс" : "child_education",
   "строительные материалы" : "sci_tech",
   "алгебра 9 класс" : "child_education",
   "биографические справочники" : "ref_ref",
   "зарубежная классика" : "foreign_prose",
   "спиритизм, пророчества и предсказания" : "religion_esoterics",
   "общественно-политические справочники" : "ref_ref",
   "атомная энергетика" : "sci_tech",
   "психологические тренинги" : "psy_personal",
   "орфоэпические словари" : "ref_dict",
   "конструкции" : "sci_tech",
   "интернет" : "comp_www",
   "техническая литература" : "sci_tech",
   "основы культуры России 4 класс" : "child_education",
   "ЕГЭ по обществознанию" : "child_education",
   "молитвы в исламе" : "religion",
   "геология" : "geography_book",
   "управление продажами" : "marketing",
   "слияния и поглощения" : "popular_business",
   "внешняя политика" : "sci_politics",
   "учебно-методические пособия (методички)" : "pedagogy_book",
   "русский язык 11 класс" : "child_education",
   "ЕГЭ по иностранному языку" : "child_education",
   "детские приключения" : "child_adv",
   "эзотерика, оккультизм" : "religion_esoterics",
   "химия 10 класс" : "child_education",
   "корпоративная культура" : "org_behavior",
   "ортопедия и травматология" : "sci_medicine",
   "отдых / туризм" : "home_crafts",
   "ценные бумаги / инвестиции" : "stock",
   "производство рыбы" : "sci_tech",
   "европейская старинная литература" : "antique_european",
   "сельское хозяйство" : "sci_biology",
   "промышленность" : "sci_tech",
   "микроэкономика" : "economics",
   "математика 6 класс" : "child_education",
   "проектирование в строительстве" : "sci_tech",
   "основы безопасности жизнедеятельности (ОБЖ) 8 класс" : "child_education",
   "недвижимость" : "real_estate",
   "фольклор" : "antique",
   "геометрия 11 класс" : "child_education",
   "школьные учебники" : "child_education",
   "воспитание детей" : "upbringing_book",
   "Forex" : "stock",
   "секс / секс-руководства" : "home_sex",
   "научные справочники" : "ref_ref",
   "предпринимательское право" : "sci_juris",
   "физкультура 3 класс" : "child_education",
   "конфликты" : "management",
   "выход из бизнеса" : "popular_business",
   "о психологии популярно" : "psy_generic",
   "производственный менеджмент" : "management",
   "вирусология" : "sci_medicine",
   "изобразительное искусство" : "visual_arts",
   "музыка 5 класс" : "child_education",
   "русский язык 8 класс" : "child_education",
   "литература 20 века" : "literature_20",
   "классический маркетинг" : "marketing",
   "изобразительное искусство (ИЗО) 4 класс" : "child_education",
   "ГИА по истории (ОГЭ, ГВЭ)" : "child_education",
   "русский язык как иностранный" : "foreign_language",
   "зарубежная прикладная литература" : "foreign_home",
   "изобразительное искусство (ИЗО) 3 класс" : "child_education",
   "нейробиология" : "sci_biology",
   "литература 19 века" : "literature_19",
   "школьные учебники по риторике" : "child_education",
   "консалтинг" : "popular_business",
   "технология 4 класс" : "child_education",
   "буддизм" : "religion",
   "организационный менеджмент" : "management",
   "медицина" : "sci_medicine",
   "технический анализ" : "personal_finance",
   "история 6 класс" : "child_education",
   "физкультура 2 класс" : "child_education",
   "компьютерные журналы" : "periodic",
   "детские детективы" : "child_det",
   "мировая художественная культура (МХК) 10 класс" : "child_education",
   "ужасы, мистика" : "sf_horror",
   "русский язык 4 класс" : "child_education",
   "холодные продажи" : "marketing",
   "обществознание 9 класс" : "child_education",
   "школьные учебники по русскому языку" : "child_education",
   "сельское и лесное хозяйство" : "sci_biology",
   "иностранный язык 6 класс" : "child_education",
   "основы производства" : "sci_tech",
   "эротическое фэнтези" : "love_erotica",
   "археология" : "sci_history",
   "зарубежная старинная литература" : "foreign_antique",
   "ГИА по биологии (ОГЭ, ГВЭ)" : "child_education",
   "логистика" : "economics",
   "физкультура 11 класс" : "child_education",
   "учебники 11 класс" : "child_education",
   "клиническая медицина" : "sci_medicine",
   "тимбилдинг" : "management",
   "крахмалопаточное производство" : "sci_tech",
   "иммунология и аллергология" : "sci_medicine",
   "основы безопасности жизнедеятельности (ОБЖ) 5 класс" : "child_education",
   "история права" : "sci_juris",
   "основы культуры России 5 класс" : "child_education",
   "французский язык" : "foreign_language",
   "истории успеха и биографии" : "popular_business",
   "зарубежная образовательная литература" : "foreign_edu",
   "военное право" : "sci_juris",
   "детская психология" : "psy_childs",
   "технология 7 класс" : "child_education",
   "управление персоналом и лидерство" : "popular_business",
   "философия" : "sci_philosophy",
   "музыка 4 класс" : "child_education",
   "экономика развитых стран" : "economics",
   "технология 5 класс" : "child_education",
   "контркультура" : "prose_counter",
   "обществознание 6 класс" : "child_education",
   "зарубежное фэнтези" : "foreign_fantasy",
   "журналы о досуге и развлечениях" : "periodic",
   "физкультура 5 класс" : "child_education",
   "корпоративные финансы" : "personal_finance",
   "конституционное право" : "sci_juris",
   "автоматика и телемеханика" : "sci_tech",
   "советская литература" : "prose_su_classics",
   "детские журналы" : "periodic",
   "школьные учебники по черчению" : "child_education",
   "православная медицина" : "religion",
   "социокультурная деятельность" : "sci_culture",
   "метафизика" : "sci_philosophy",
   "учебники 5 класс" : "child_education",
   "юриспруденция" : "sci_juris",
   "законы и постановления" : "sci_juris",
   "детская проза" : "child_prose",
   "эротическая литература" : "home_sex",
   "чтение 3 класс" : "child_education",
   "первобытное общество" : "sci_history",
   "зарубежная литература о культуре и искусстве" : "foreign_home",
   "школьные учебники по основам нравственной культуры России" : "child_education",
   "история психологии" : "psy_generic",
   "химия 9 класс" : "child_education",
   "иностранный язык 2 класс" : "child_education",
   "морские приключения" : "adv_maritime",
   "уголовно-процессуальное право" : "sci_juris",
   "биология 8 класс" : "child_education",
   "коучинг" : "management",
   "экономическая статистика" : "economics",
   "производство птицы" : "sci_tech",
   "школьные учебники по геометрии" : "child_education",
   "информационная безопасность" : "computers",
   "список школьной литературы 5-6 класс" : "child_education",
   "ЕГЭ по математике" : "sci_math",
   "школьные учебники по алгебре" : "child_education",
   "космический транспорт" : "sci_tech",
   "воскресная школа" : "sci_religion",
   "изучение языков" : "foreign_language",
   "зарубежный юмор" : "foreign_humor",
   "электроакустика" : "sci_tech",
   "бродильные производства" : "sci_tech",
   "история экономики" : "economics",
   "таможенный кодекс РФ" : "sci_juris",
   "информатика и вычислительная техника" : "sci_tech",
   "хронология" : "sci_history",
   "общая история" : "sci_history",
   "искусство фотографии" : "visual_arts",
   "книги о войне" : "prose_military",
   "нормативные правовые акты" : "sci_juris",
   "криминальные боевики" : "det_crime",
   "физика 8 класс" : "child_education",
   "учебники 10 класс" : "child_education",
   "эзотерика" : "religion_esoterics",
   "управление экономикой" : "economics",
   "лояльность" : "marketing",
   "православие для детей" : "sci_religion",
   "компьютерное железо" : "comp_hard",
   "государственное и муниципальное управление" : "management",
   "школьные учебники по окружающему миру" : "child_education",
   "муниципальное право" : "sci_juris",
   "сахарное производство" : "sci_tech",
   "трудовой кодекс РФ" : "sci_juris",
   "школьные учебники по литературе" : "child_education",
   "бухучет / налогообложение / аудит" : "accounting",
   "учебники 7 класс" : "child_education",
   "новое время" : "sci_history",
   "фанфик" : "unrecognised",
   "литература 8 класс" : "child_education",
   "школьные учебники по физике" : "child_education",
   "геронтология" : "sci_medicine",
   "школьные учебники по чтению" : "child_education",
   "православные молитвы" : "religion_rel",
   "классические детективы" : "det_classic",
   "английский язык" : "foreign_language",
   "альтернативная медицина" : "home_health",
   "зарубежная фантастика" : "foreign_sf",
   "книги для дошкольников" : "children",
   "историческая литература" : "prose_history",
   "информатика 4 класс" : "child_education",
   "переговоры" : "psy_personal",
   "финансовое право" : "sci_juris",
   "фармакология" : "sci_medicine",
   "материалы конференций" : "science",
   "PR" : "marketing",
   "страховое право" : "sci_juris",
   "героическое фэнтези" : "sf_heroic",
   "старинная литература" : "antique",
   "наркология" : "sci_medicine",
   "криминалистика" : "sci_juris",
   "технологии металлов" : "sci_tech",
   "изобразительное искусство (ИЗО) 1 класс" : "child_education",
   "бизнес-журналы" : "periodic",
   "охотничье хозяйство" : "sci_biology",
   "опера, балет" : "music_dancing",
   "кулинария" : "home_cooking",
   "переработка плодов, овощей" : "sci_tech",
   "правоведение" : "sci_juris",
   "практическая психология" : "psy_theraphy",
   "IPO" : "personal_finance",
   "биология 10 класс" : "child_education",
   "география 6 класс" : "child_education",
   "эротика ЛГБТ" : "home_sex",
   "право 11 класс" : "child_education",
   "школьные учебники по информатике" : "child_education",
   "информатика 2 класс" : "child_education",
   "детская познавательная и развивающая литература" : "children",
   "иностранный язык 8 класс" : "child_education",
   "русский язык 5 класс" : "child_education",
   "энциклопедические словари" : "ref_dict",
   "автомобили и ПДД" : "auto_regulations",
   "зарубежные любовные романы" : "foreign_love",
   "поиск работы / карьера" : "job_hunting",
   "эротические рассказы и истории" : "love_erotica",
   "аналитическая химия" : "sci_chem",
   "программирование" : "comp_programming",
   "богословие" : "sci_religion",
   "историческая фантастика" : "sf_history",
   "автотранспорт" : "sci_tech",
   "рабочие тетради, прописи" : "child_education",
   "венерология" : "sci_medicine",
   "история 5 класс" : "child_education",
   "психотерапия" : "psy_theraphy",
   "легкая промышленность" : "sci_tech",
   "сад и огород" : "home_garden",
   "информатика 5 класс" : "child_education",
   "внутренняя политика" : "sci_politics",
   "кондитерское производство" : "sci_tech",
   "фармация" : "sci_medicine",
   "классическая проза" : "prose_classic",
   "криминология" : "sci_juris",
   "школьные учебники по чистописанию" : "child_education",
   "маркетинг и реклама" : "popular_business",
   "кодекс РФ об административных правонарушениях" : "sci_juris",
   "ЕГЭ по биологии" : "child_education",
   "финансовые инструменты" : "stock",
   "МСФО" : "personal_finance",
   "ГИА по иностранному языку (ОГЭ, ГВЭ)" : "child_education",
   "школьные учебники по краеведению" : "child_education",
   "радиотехника" : "sci_tech",
   "зарубежная деловая литература" : "foreign_business",
   "краткое содержание" : "popular_business",
   "финансово-экономические журналы" : "periodic",
   "школьные учебники по естествознанию" : "child_education",
   "хирургия" : "sci_medicine",
   "польский язык" : "foreign_language",
   "учебники 2 класс" : "child_education",
   "музыка 3 класс" : "child_education",
   "основы психологии" : "psy_generic",
   "сборник кодексов РФ" : "sci_juris",
   "книги для подростков" : "children",
   "саморазвитие / личностный рост" : "psy_personal",
   "Конституция РФ" : "sci_juris",
   "дерматология" : "sci_medicine",
   "эффективность бизнеса" : "popular_business",
   "гигиена" : "sci_medicine",
   "современная русская литература" : "russian_contemporary",
   "общетехнические дисциплины" : "sci_tech",
   "русская классика" : "prose_rus_classic",
   "словари" : "ref_dict",
   "биобиблиографические справочники" : "ref_ref",
   "литература 5 класс" : "child_education",
   "алгебра 7 класс" : "child_education",
   "технология 11 класс" : "child_education",
   "общая биология" : "sci_biology",
   "охота" : "home_crafts",
   "технология 3 класс" : "child_education",
   "учебные справочники" : "ref_ref",
   "зоология" : "sci_biology",
   "менеджмент" : "management",
   "рыбное хозяйство" : "sci_biology",
   "гидроэнергетика" : "sci_tech",
   "бюджетный кодекс РФ" : "sci_juris",
   "исторические любовные романы" : "love_history",
   "органы юстиции" : "sci_juris",
   "физика 10 класс" : "child_education",
   "электроэнергетика" : "sci_tech",
   "мировая художественная культура (МХК) 11 класс" : "child_education",
   "успешные переговоры" : "marketing",
   "остросюжетные любовные романы" : "love_detective",
   "библиографические справочники" : "ref_ref",
   "иностранный язык 5 класс" : "child_education",
   "биология 9 класс" : "child_education",
   "литературоведение" : "sci_linguistic",
   "школьные учебники по немецкому языку" : "child_education",
   "путеводители" : "geo_guides",
   "изобразительное искусство (ИЗО) 8 класс" : "child_education",
   "книги по философии" : "sci_philosophy",
   "литература 9 класс" : "child_education",
   "финансовый менеджмент" : "management",
   "школьные учебники по английскому языку" : "child_education",
   "политология" : "sci_politics",
   "оториноларингология" : "sci_medicine",
   "любовное фэнтези" : "love_fantasy",
   "музыка 1 класс" : "child_education",
   "школьные учебники по изобразительному искусству (ИЗО)" : "child_education",
   "газеты" : "newspapers",
   "информатика 1 класс" : "child_education",
   "химия полимеров" : "sci_chem",
   "личная эффективность" : "religion_self",
   "ГИА по информатике и ИКТ (ОГЭ, ГВЭ)" : "child_education",
   "палеонтология" : "sci_biology",
   "русское фэнтези" : "russian_fantasy",
   "безалкогольные напитки" : "sci_tech",
   "журналы" : "periodic",
   "магия, колдовство" : "religion_esoterics",
   "юридические журналы" : "periodic",
   "уголовный кодекс РФ" : "sci_juris",
   "состояния и явления психики" : "psy_theraphy",
   "технические науки" : "sci_tech",
   "генетика" : "sci_biology",
   "природа и животные" : "adv_animal",
   "СМИ" : "sci_culture",
   "анатомия и физиология" : "sci_biology",
   "пищевая промышленность" : "sci_tech",
   "основы строительства" : "sci_tech",
   "технология 8 класс" : "child_education",
   "история философии" : "sci_philosophy",
   "химия 7 класс" : "child_education",
   "здоровый образ жизни  / фитнес" : "popular_business",
   "чистописание 1 класс" : "child_education",
   "классики психологии" : "psy_alassic",
   "бизнес-стратегии" : "popular_business",
   "налоговый кодекс РФ" : "sci_juris",
   "клиническая психология" : "psy_theraphy",
   "школьные учебники по географии" : "child_education",
   "военное дело" : "science",
   "литература 11 класс" : "child_education",
   "древнерусская литература" : "antique_russian",
   "урология и нефрология" : "sci_medicine",
   "русская поэзия" : "poetry",
   "эффективная презентация" : "marketing",
   "география 8 класс" : "child_education",
   "русский язык 6 класс" : "child_education",
   "семейная психология" : "psy_sex_and_family",
   "русский язык 9 класс" : "child_education",
   "обществознание 11 класс" : "child_education",
   "экология 10 класс" : "child_education",
   "православные традиции" : "religion_rel",
   "экономическое развитие" : "economics",
   "авторефераты диссертаций" : "home_garden",
   "разговорники" : "ref_dict",
   "литература для внеклассного чтения" : "child_education",
   "производственно-практические издания" : "ref_ref",
   "современные религиозные течения" : "religion",
   "анестезиология" : "sci_medicine",
   "воздушный транспорт" : "sci_tech",
   "история православной церкви" : "religion",
   "музыка 2 класс" : "child_education",
   "телевидение" : "cinema_theatre",
   "аналитические журналы" : "periodic",
   "маркетинг, PR, реклама" : "marketing",
   "геометрия 9 класс" : "child_education",
   "литература 6 класс" : "child_education",
   "рыбалка" : "home_crafts",
   "иностранный язык 10 класс" : "child_education",
   "современное политическое положение" : "sci_politics",
   "физкультура и спорт" : "science",
   "биология 6 класс" : "child_education",
   "управление ассортиментом" : "marketing",
   "учебная литература" : "child_education",
   "православные календари" : "religion",
   "школьные учебники по технологии" : "child_education",
   "чтение 2 класс" : "child_education",
   "религиозные тексты" : "religion_rel",
   "химия 11 класс" : "child_education",
   "история Древнего мира" : "sci_history",
   "физкультура 10 класс" : "child_education",
   "практикумы" : "science",
   "акционерное право" : "sci_juris",
   "юмористические стихи" : "humor_verse",
   "боевое фэнтези" : "fantasy_fight",
   "арбитражное процессуальное право" : "sci_juris",
   "процессы и аппараты химической технологии" : "sci_tech",
   "бизнес-процессы" : "management",
   "здоровое и правильное питание" : "home_health",
   "история 8 класс" : "child_education",
   "юмористическая проза" : "humor_prose",
   "мифы, легенды, эпос" : "antique_myths",
   "обществознание 8 класс" : "child_education",
   "экология" : "sci_biology",
   "языковые словари" : "ref_dict",
   "финансы, инвестиции, экономика" : "popular_business",
   "кризисное управление" : "management",
   "акафисты" : "religion_rel",
   "IT-менеджмент" : "management",
   "школьные учебники по правоведению" : "child_education",
   "неврология" : "sci_medicine",
   "политические партии" : "sci_politics",
   "зарубежные детективы" : "foreign_detective",
   "привлечение инвестиций" : "popular_business",
   "металлургия" : "sci_tech",
   "книги для священнослужителей" : "religion_rel",
   "партизанский маркетинг" : "marketing",
   "окружающий мир 2 класс" : "child_education",
   "коллоидная химия" : "sci_chem",
   "технология 1 класс" : "child_education",
   "материаловедение" : "sci_tech",
   "MBA" : "management",
   "школьные учебники по обществознанию" : "child_education",
   "project-менеджмент" : "management",
   "уголовно-процессуальный кодекс РФ" : "sci_juris",
   "хлебопечение" : "sci_tech",
   "основы безопасности жизнедеятельности (ОБЖ) 6 класс" : "child_education",
   "ГИА по физике (ОГЭ, ГВЭ)" : "child_education",
   "музыка 8 класс" : "child_education",
   "стоматология" : "sci_medicine",
   "транзакционный анализ" : "psy_theraphy",
   "школьные учебники по экологии" : "child_education",
   "социология" : "sociology_book",
   "техника продаж" : "marketing",
   "музыка 9 класс" : "child_education",
   "зарубежные детские книги" : "foreign_children",
   "школьные учебники по музыке" : "child_education",
   "экология 8 класс" : "child_education",
   "справочники" : "ref_ref",
   "научно-популярная литература" : "science",
   "горное дело" : "sci_tech",
   "строительство" : "sci_tech",
   "экономический анализ" : "economics",
   "семейное право" : "sci_juris",
   "арбитражный процессуальный кодекс РФ" : "sci_juris",
   "юмор и сатира" : "humor",
   "алгебра 11 класс" : "child_education",
   "терминологические словари" : "ref_dict",
   "историческое фэнтези" : "historical_fantasy",
   "крупяное производство" : "sci_tech",
   "стартапы и создание бизнеса" : "popular_business",
   "современная зарубежная литература" : "foreign_contemporary",
   "управление бизнесом" : "management",
   "общественное питание" : "sci_tech",
   "трудовое право" : "sci_juris",
   "базы данных" : "comp_db",
   "тайм-менеджмент" : "religion_self",
   "просто о бизнесе" : "popular_business",
   "информатика 6 класс" : "child_education",
   "мистика" : "sf_horror",
   "учебники 8 класс" : "child_education",
   "литература 10 класс" : "child_education",
   "окружающий мир 3 класс" : "child_education",
   "публицистика" : "nonf_publicism",
   "бизнес-процессы / инновации" : "popular_business",
   "ГИА (ОГЭ, ГВЭ)" : "child_education",
   "советы от гуру" : "popular_business",
   "естествознание 11 класс" : "child_education",
   "общая патология" : "sci_medicine",
   "математика" : "sci_math",
   "ГИА по литературе (ОГЭ, ГВЭ)" : "child_education",
   "самоучители" : "child_education",
   "алгебра 8 класс" : "child_education",
   "ГИА по химии (ОГЭ, ГВЭ)" : "child_education",
   "химия 8 класс" : "child_education",
   "даосизм, конфуцианство" : "religion_rel",
   "геометрия 10 класс" : "child_education",
   "математика 4 класс" : "child_education",
   "мужские журналы" : "periodic",
   "лидерство" : "management",
   "русский язык 10 класс" : "child_education",
   "экономика развивающихся стран" : "economics",
   "педиатрия и неонатология" : "sci_medicine",
   "трубопроводный транспорт" : "sci_tech",
   "иностранный язык 9 класс" : "child_education",
   "реаниматология" : "sci_medicine",
   "дистрибуция" : "marketing",
   "о бизнесе популярно" : "popular_business",
   "менеджмент и кадры" : "management",
   "книги про вампиров" : "vampire_book",
   "история 10 класс" : "child_education",
   "иностранный язык 7 класс" : "child_education",
   "событийный маркетинг" : "marketing",
   "кадровый менеджмент" : "management",
   "вероучения в буддизме" : "religion",
   "зарубежная публицистика" : "foreign_publicism",
   "экономика 11 класс" : "child_education",
   "детективное фэнтези" : "sf_detective",
   "акушерство и гинекология" : "sci_medicine",
   "зарубежная религиозная и эзотерическая литература" : "foreign_religion",
   "русский язык 2 класс" : "child_education",
   "асептика и антисептика" : "sci_medicine",
   "изобразительное искусство (ИЗО) 9 класс" : "child_education",
   "педагогика" : "pedagogy_book",
   "рукоделие и ремесла" : "home_crafts",
   "иностранный язык 4 класс" : "child_education",
   "школьные методические пособия" : "child_education",
   "производство мяса" : "sci_tech",
   "креатив, идеи" : "popular_business",
   "короткие любовные романы" : "love_short",
   "школьные учебники по химии" : "child_education",
   "основы безопасности жизнедеятельности (ОБЖ) 7 класс" : "child_education",
   "административное право" : "sci_juris",
   "физика" : "sci_phys",
   "электрическая связь" : "sci_tech",
   "гражданское право" : "sci_juris",
   "энергетика" : "sci_tech",
   "киберпанк" : "sf_cyberpunk",
   "уголовное право" : "sci_juris",
   "книги о приключениях" : "adventure",
   "зарубежная справочная литература" : "foreign_desc",
   "география 10 класс" : "child_education",
   "математика 1 класс" : "child_education",
   "ГИА по математике (ОГЭ, ГВЭ)" : "child_education",
   "право 10 класс" : "child_education",
   "компьютерная справочная литература" : "ref_ref",
   "биология" : "sci_biology",
   "офтальмология" : "sci_medicine",
   "музыка 6 класс" : "child_education",
   "справочная литература" : "reference",
   "список школьной литературы 9 класс" : "child_education",
   "похудение и диеты" : "home_sport",
   "обществознание 10 класс" : "child_education",
   "брендинг" : "marketing",
   "ужасы" : "sf_horror",
   "строительные конструкции" : "sci_tech",
   "общественные организации" : "sci_politics",
   "героическая фантастика" : "sf_heroic",
   "гастроэнтерология" : "sci_medicine",
   "руководства" : "ref_guide",
   "маркетинг для новичков" : "marketing",
   "национальная политика" : "sci_politics",
   "налоговое право" : "sci_juris",
   "обогащение полезных ископаемых" : "sci_tech",
   "популярные справочники" : "ref_ref",
   "банковское дело" : "banking",
   "организация офиса" : "popular_business",
   "учебные программы" : "child_education",
   "орфографические словари" : "ref_dict",
   "зарубежная поэзия" : "foreign_poetry",
   "психиатрия" : "psy_theraphy",
   "ГИА по русскому языку (ОГЭ, ГВЭ)" : "child_education",
   "ЕГЭ по физике" : "child_education",
   "соционика" : "psy_social",
   "боевики" : "det_action",
   "психологическая консультация" : "psy_theraphy",
   "химическая технология" : "sci_tech",
   "экономика" : "economics",
   "ГИА по обществознанию (ОГЭ, ГВЭ)" : "child_education",
   "стратегия маркетинга" : "marketing",
   "учебники и пособия для вузов" : "child_education",
   "домашние животные" : "home_pets",
   "общая экономическая теория" : "economics",
   "производство молока" : "sci_tech",
   "физика 7 класс" : "child_education",
   "спорт / фитнес" : "home_sport",
   "юмористическая фантастика" : "sf_humor",
   "информатика 7 класс" : "child_education",
   "танцы" : "music_dancing",
   "управление маркетингом" : "marketing",
   "исторические детективы" : "det_history",
   "детская фантастика" : "child_sf",
   "директ-маркетинг" : "marketing",
   "школьные учебники по основам безопасности жизнедеятельности (ОБЖ)" : "child_education",
   "отдельные виды строительства" : "sci_tech",
   "стратегический менеджмент" : "management",
   "музыка" : "music_dancing",
   "уголовно-исполнительный кодекс РФ" : "sci_juris",
   "отношения с клиентами" : "marketing",
   "реклама" : "marketing",
   "основы безопасности жизнедеятельности (ОБЖ) 10 класс" : "child_education",
   "интернет-бизнес" : "marketing",
   "политическое управление" : "management",
   "онкология" : "sci_medicine",
   "семейный кодекс РФ" : "sci_juris",
   "японский менеджмент" : "management",
   "книги о путешествиях" : "adv_geo",
   "Священное Писание" : "religion_rel",
   "маркетинговые исследования и анализ" : "marketing",
   "городское фэнтези" : "city_fantasy",
   "таинственные явления" : "religion_esoterics",
   "искусствоведение" : "visual_arts",
   "экология 11 класс" : "child_education",
   "попаданцы" : "popadanec",
   "женские журналы" : "periodic",
   "управление качеством" : "management",
   "личная эффективность / продуктивность" : "popular_business",
   "духовная литература" : "religion",
   "разработка месторождений" : "sci_tech",
   "боевая фантастика" : "sf_action",
   "источниковедение" : "sci_history",
   "земельный кодекс РФ" : "sci_juris",
   "эпидемиология" : "sci_medicine",
   "крутой детектив" : "det_hard",
   "ЕГЭ" : "child_education",
   "cемья, дети, воспитание" : "popular_business",
   "клиентский сервис" : "marketing",
   "ЕГЭ по истории" : "child_education",
   "мукомольное производство" : "sci_tech",
   "дизайн" : "visual_arts",
   "жилищный кодекс РФ" : "sci_juris",
   "музыка 7 класс" : "child_education",
   "парапсихология" : "religion_esoterics",
   "журналы о доме и семье" : "periodic",
   "радиолокация" : "sci_tech",
   "научно-популярные журналы" : "periodic",
   "биохимия" : "sci_chem",
   "технология органических веществ" : "sci_tech",
   "животноводство" : "sci_biology",
   "религиозные журналы" : "periodic",
   "тайные общества" : "religion_esoterics",
   "фэн-шуй" : "religion_esoterics",
   "ораторское искусство / риторика" : "psy_personal",
   "языкознание" : "sci_linguistic",
   "альманахи" : "periodic",
   "эротика и секс" : "home_sex",
   "паломничество" : "religion",
   "гражданское процессуальное право" : "sci_juris",
   "история Средних веков" : "sci_history",
   "технические справочники" : "ref_ref",
   "частотные словари" : "ref_dict",
   "зарубежная психология" : "foreign_psychology",
   "теплоэнергетика" : "sci_tech",
   "другие словари" : "ref_dict",
   "аттестация персонала" : "management",
   "прочая образовательная литература" : "science",
   "изобразительное искусство (ИЗО) 5 класс" : "child_education",
   "этимологические словари" : "ref_dict",
   "ботаника" : "sci_biology",
   "отраслевая и межотраслевая экономика" : "economics",
   "зарубежная религиозная литература" : "foreign_religion",
   "делопроизводство" : "paper_work",
   "новейшая история" : "sci_history",
   "дзэн-буддизм" : "religion",
   "программы" : "comp_soft",
   "привлечение клиентов" : "marketing",
   "окружающий мир 4 класс" : "child_education",
   "наука и технологии" : "popular_business",
   "токсикология" : "sci_medicine",
   "немецкий язык" : "foreign_language",
   "product placement" : "marketing",
   "энциклопедии" : "ref_encyc",
   "география 9 класс" : "child_education",
   "русский язык 3 класс" : "child_education",
   "истории успеха" : "popular_business",
   "иронические детективы" : "det_irony",
   "психология" : "popular_business",
   "отраслевая психология" : "psy_generic",
   "экономическая география" : "economics",
   "зарубежные боевики" : "foreign_action",
   "экономика 10 класс" : "child_education",
   "документальная литература" : "nonfiction",
   "идеографические словари" : "ref_dict",
   "приборостроение" : "sci_tech",
   "таможенное право" : "sci_juris",
   "история 9 класс" : "child_education",
   "кибернетика" : "sci_tech",
   "ГИА по географии (ОГЭ, ГВЭ)" : "child_education",
   "история политических учений" : "sci_politics",
   "астрология" : "religion_esoterics",
   "парикмахерское дело" : "home",
   "социальная философия" : "sci_philosophy",
   "задачники" : "child_education",
   "основы безопасности жизнедеятельности (ОБЖ) 11 класс" : "child_education",
   "информатика 11 класс" : "child_education",
   "научно-практические журналы" : "periodic",
   "возрастная психология" : "psy_generic",
   "технология 2 класс" : "child_education",
   "внеклассное чтение" : "child_education",
   "учебники 3 класс" : "child_education",
   "производство вкусовых продуктов" : "sci_tech",
   "политические детективы" : "det_political",
   "трейдинг" : "personal_finance",
   "общая химия" : "sci_chem",
   "кардиология" : "sci_medicine",
   "прикладные отрасли медицины" : "sci_medicine",
   "история искусств" : "visual_arts",
   "информатика 9 класс" : "child_education",
   "поиск и подбор персонала" : "management",
   "литература 18 века" : "literature_18",
   "cтихи и поэзия" : "poetry",
   "критика" : "nonf_criticism",
   "развлечения" : "home_entertain",
   "сказки" : "child_tale",
   "древневосточная литература" : "antique_east",
   "эротические романы" : "love_erotica",
   "религии, верования, культы" : "religion",
   "юмористическое фэнтези" : "humor_fantasy",
   "вестерны" : "adv_western",
   "личные финансы" : "personal_finance",
   "работа с клиентами" : "popular_business",
   "учебники 1 класс" : "child_education",
   "история экономических учений" : "economics",
   "чтение 4 класс" : "child_education",
   "всемирная история" : "sci_history",
   "ОС и сети" : "comp_osnet",
   "бюджетирование" : "personal_finance",
   "любовь и отношения" : "psy_sex_and_family",
   "антропология" : "sci_biology",
   "мотивация" : "management",
   "квантовая электроника" : "sci_tech",
   "зарубежные приключения" : "foreign_adventure",
   "география 5 класс" : "child_education",
   "космическая фантастика" : "sf_space",
   "монографии" : "science",
   "управление персоналом" : "management",
   "машиностроение" : "sci_tech",
   "городской транспорт" : "sci_tech",
   "макроэкономика" : "economics",
   "изобразительное искусство (ИЗО) 6 класс" : "child_education",
   "сделай сам" : "home_diy",
   "античная литература" : "antique_ant",
   "железнодорожный транспорт" : "sci_tech",
   "социальная психология" : "psy_social",
   "литературные журналы" : "periodic",
   "российская практика" : "popular_business",
   "хобби / увлечения" : "home_crafts",
   "уголовно-исполнительное право" : "sci_juris",
   "земельное право" : "sci_juris",
   "юридическая литература" : "sci_juris",
   "мода и стиль" : "home",
   "микробиология" : "sci_medicine",
   "иностранный язык 3 класс" : "child_education",
   "литература 7 класс" : "child_education",
   "школьные учебники по физической культуре" : "child_education",
   "работа с долгами" : "popular_business",
   "список школьной литературы 10-11 класс" : "child_education",
   "география 7 класс" : "child_education",
   "география" : "geography_book",
   "этнография" : "sci_history",
   "нормативная документация" : "sci_tech",
   "агрохимия" : "sci_biology",
   "история 11 класс" : "child_education",
   "классика приключенческой литературы" : "adventure",
   "паразитология" : "sci_medicine",
   "интернет-маркетинг" : "marketing",
   "производство консервов" : "sci_tech",
   "ЕГЭ по русскому языку" : "child_education",
   "книги по экономике" : "economics",
   "школьные учебники по мировой художественной культуре (МХК)" : "child_education",
   "технология 9 класс" : "child_education",
   "геометрия 7 класс" : "child_education",
   "прически, уход за волосами" : "home",
   "биология 7 класс" : "child_education",
   "книги о компьютерах" : "computers",
   "школьные учебники по французскому языку" : "child_education",
   "изобразительное искусство (ИЗО) 7 класс" : "child_education",
   "технология строительного производства" : "sci_tech",
   "учебники 6 класс" : "child_education",
   "математика 5 класс" : "child_education",
   "физкультура 1 класс" : "child_education",
   "коммерческое право" : "sci_juris",
   "зарубежная драматургия" : "foreign_dramaturgy",
   "обществознание 5 класс" : "child_education",
   "пищевое производство" : "sci_tech",
   "медицинские журналы" : "periodic",
   "ЕГЭ по литературе" : "child_education",
   "водный транспорт" : "sci_tech",
   "русская драматургия" : "dramaturgy",
   "военное дело, спецслужбы" : "military_special",
   "физкультура 8 класс" : "child_education",
   "этика" : "sci_philosophy",
   "учебники 4 класс" : "child_education",
   "итальянский язык" : "foreign_language",
   "малый бизнес" : "small_business",
   "бизнес-план" : "popular_business",
   "Ислам, мусульманство" : "religion",
   "законы, нормативные акты" : "sci_juris",
   "переговоры и продажи" : "popular_business",
   "конституция и кодексы РФ" : "sci_juris",
   "музеи и коллекции" : "visual_arts",
   "христианское искусство" : "religion",
   "сжатые и разреженные газы" : "sci_tech",
   "естествознание 5 класс" : "child_education",
   "исторические приключения" : "adv_history",
   "детективная фантастика" : "sf_detective",
   "анекдоты" : "humor_anecdote",
   "историческая научная и учебная литература" : "sci_history",
   "медицина, здравоохранение" : "sci_medicine",
   "эстетика" : "sci_philosophy",
   "механика" : "sci_phys",
   "математика 3 класс" : "child_education",
   "испанский язык" : "foreign_language",
   "физкультура 4 класс" : "child_education",
   "школьные учебники по биологии" : "child_education",
   "физика 9 класс" : "child_education",
   "география 11 класс" : "child_education",
   "иностранный язык 1 класс" : "child_education",
   "растениеводство" : "sci_biology",
   "список школьной литературы 7-8 класс" : "child_education",
   "копирайтинг" : "marketing",
   "алгебра 10 класс" : "child_education",
   "фэнтези про драконов" : "dragon_fantasy",
   "здоровье" : "home_health",
   "технология неорганических веществ" : "sci_tech",
   "финансы" : "stock",
   "зарубежная компьютерная литература" : "foreign_comp",
   "косметика и косметология" : "home_health",
   "современные детективы" : "detective",
   "журнальные издания" : "periodic",
   "психология управления" : "psy_social",
   "отраслевые издания" : "industries",
   "политика" : "sci_politics",
   "биология 5 класс" : "child_education"
}
